### ISSUE TITLE
Manage 1.6.2+ Account Link Controller Depends On Next Release of erchef/Chef 12.0.x

### ISSUE THREAD

**Issue by sean-horn** [opscode/chef-server#41]
The fix is at https://github.com/opscode/oc_chef_wm/commit/37887e492f3f0939f7afe6ca48e2df051175c127

In order for LDAP account linking to completely work, we need to release this in a version of Chef Server 12 > 12.0.0

**Comment by smith** [comment]
Moved this to another (internal only) board: https://chef.leankit.com/Boards/View/157948591/151867788

**Comment by smith** [comment]
Verified this is working on Chef Server 12.0.1.
