### ISSUE TITLE
upgrade from 11 to 12 fails

### ISSUE THREAD

**Issue by gokulnath** [opscode/chef-server#61]
OS: ubuntu 12.04
old chef version: 11.0.8
new chef version: 12.0.1
instructions used for upgrade: https://docs.chef.io/upgrade_server.html#from-chef-server-osc
```
$ sudo chef-server-ctl upgrade
the ffi-yajl and yajl-ruby gems have incompatible C libyajl libs and should not be loaded in the same Ruby VM
falling back to ffi which might work (or might not, no promises)
ffi-yajl/json_gem is deprecated, these monkeypatches will be dropped shortly
Upgrading with options #<OpenStruct skip_confirmation=false, chef11_server_url="https://localhost", chef12_server_url="https://localhost", upload_threads=10, chef11_admin_client_name="admin", chef11_admin_client_key="/etc/chef-server/admin.pem">
Open source Chef 11 server detected.
Would you like to upgrade? [yN]
y
Upgrading the open source Chef 11 server.
Chef 12 short organization name? mobme
Chef 12 full organization name? MobME Wireless solutions
Creating /tmp/chef11-server-data20150115-12709-1jyp3j3 as the location to save the open source Chef 11 server data
Ensuring Chef 12 server is stopped
the ffi-yajl and yajl-ruby gems have incompatible C libyajl libs and should not be loaded in the same Ruby VM
falling back to ffi which might work (or might not, no promises)
ffi-yajl/json_gem is deprecated, these monkeypatches will be dropped shortly
Ensuring the open source Chef 11 server is started
ok: run: bookshelf: (pid 12726) 1s
ok: run: chef-expander: (pid 12742) 0s
ok: run: chef-server-webui: (pid 12746) 0s
ok: run: chef-solr: (pid 12750) 1s
ok: run: erchef: (pid 12758) 0s
ok: run: nginx: (pid 12769) 1s
ok: run: postgresql: (pid 12779) 1s
ok: run: rabbitmq: (pid 12782) 1s
Preparing knife to download data from the open source Chef 11 server
Writing knife config to /tmp/knife-config.rb for use in downloading open source Chef 11 server data
Downloading data from the open source Chef 11 server
Running knife download
ERROR: File cookbooks/var/chef is a directory while file cookbooks/var/chef is a regular file

Pulling open source Chef 11 database credentials
Finished downloading data from the open source Chef 11 server
Ensuring open source Chef 11 server is stopped
ok: down: bookshelf: 0s, normally up
ok: down: chef-expander: 0s, normally up
ok: down: chef-server-webui: 1s, normally up
ok: down: chef-solr: 0s, normally up
ok: down: erchef: 1s, normally up
ok: down: nginx: 0s, normally up
ok: down: postgresql: 1s, normally up
ok: down: rabbitmq: 0s, normally up
Open source Chef 11 server data downloaded to /tmp/chef11-server-data20150115-12709-1jyp3j3
Created /tmp/chef12-server-data20150115-12709-152dysu as the location to save the tranformed data
Transforming open source Chef 11 server data for upload to Chef 12 server
/opt/opscode/embedded/lib/ruby/1.9.1/fileutils.rb:1515:in `stat': No such file or directory - /tmp/chef11-server-data20150115-12709-1jyp3j3/users (Errno::ENOENT)
	from /opt/opscode/embedded/lib/ruby/1.9.1/fileutils.rb:1515:in `block in fu_each_src_dest'
	from /opt/opscode/embedded/lib/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
	from /opt/opscode/embedded/lib/ruby/1.9.1/fileutils.rb:1513:in `fu_each_src_dest'
	from /opt/opscode/embedded/lib/ruby/1.9.1/fileutils.rb:436:in `cp_r'
	from (eval):117:in `transform_chef11_data'
	from (eval):45:in `run_upgrade'
	from (eval):135:in `block (2 levels) in load_files'
	from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/omnibus-ctl-0.3.1/lib/omnibus-ctl.rb:177:in `call'
	from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/omnibus-ctl-0.3.1/lib/omnibus-ctl.rb:177:in `block in add_command_under_category'
	from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/omnibus-ctl-0.3.1/lib/omnibus-ctl.rb:555:in `run'
	from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/omnibus-ctl-0.3.1/bin/omnibus-ctl:31:in `<top (required)>'
	from /opt/opscode/embedded/bin/omnibus-ctl:23:in `load'
	from /opt/opscode/embedded/bin/omnibus-ctl:23:in `<main>'
```

**Comment by gokulnath** [comment]
I tried running 
`chef-server-ctl chef12-upgrade-download` 
It creates only key_dump.json in the tmp directory and not any users file/folder. 
I have databag with name users though. Not sure why it's not being downloaded as part of the above process.

**Comment by mmzyk** [comment]
@gokulnath You're going to need to upgrade your 11.0.8 Chef Server to 11.1 or greater first. The automated upgrade process has issues with any server not 11.1 or greater. It's a known issue and we've tried to stress in our docs that you need 11.1 or greater.

11.1 is the first open source 11 server that introduced the upgrade command, so you can install an 11.1 or greater server and then run chef-server-ctl upgrade and it will upgrade for you. After that you can try again the 12 upgrade.

Some information to help you with the upgrade. First, please ensure you have a backup of your data, as we don't want you to lose anything. Now, the 12 server installs into a different directory from the 11 server (12 is in /opt/opscode, whereas 11 is in /opt/chef-server/, swapping out /opt for /etc, etc. as needed). So the 11 server is still on your system and the files are still present and it is possible to start your 11 server back up. 

Chef Server 12 does point to a new chef-server-ctl, so the current chef-server-ctl on the system is expecting Chef Server 12. This is so you can run the upgrade command for Chef Server 12. The old chef-server-ctl, for the 11 server, is still on the system, in /opt/chef-server/bin I believe (trying to remember off the top of my head, but I think that's right). You can hit that chef-server-ctl direction with a start and it should bring your chef 11 server back up. 

After that, I'd recommend uninstall the chef-server-core package (this is the Chef Server 12 package) to make sure we're back to a clean state (do not uninstall the chef-server package yet, or else you will remove your Chef Server 11). Then install the Chef Server 11.1 or greater package. Then run chef-server-ctl upgrade. This will do an in place upgrade of your Chef Server 11. 

Once that is done, reinstall the chef-server-core package and run chef-server-ctl upgrade again to upgrade to Chef Server 12. This should allow you to complete your upgrade successfully.

I'm going to close this out as an issue, but if you run into problems you can comment here again and I will do my best to help you out.
